import { ToolResponse, ToolStatus } from './response';
import { ToolErrorCode } from './errors';

/**
 * 工具参数定义
 */
export interface ToolParameter {
    name: string;
    type: string;
    description: string;
    required: boolean;
    default?: any;
}

/**
 * 标记一个方法为可展开的工具 action 的装饰器选项
 */
export interface ToolActionOptions {
    name?: string;
    description?: string;
    parameters?: ToolParameter[];
}

/**
 * 装饰器：标记一个方法为可展开的工具 action
 * 
 * @param options 配置选项
 */
export function toolAction(options: ToolActionOptions = {}) {
    return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {
        const method = descriptor.value;
        method._isToolAction = true;
        method._toolName = options.name;
        method._toolDescription = options.description;
        method._toolParameters = options.parameters;
        return descriptor;
    };
}

/**
 * 工具基类
 * 
 * 支持两种使用模式：
 * 1. 普通模式：工具作为单一实体使用
 * 2. 可展开模式：工具可以展开为多个独立的子工具（每个子工具对应一个功能）
 */
export abstract class Tool {
    name: string;
    description: string;
    expandable: boolean;

    /**
     * 初始化工具
     * 
     * 允许子类采用两种模式：
     * 1. 显式调用 super(name, description, expandable)
     * 2. 像 Python 版本一样仅覆写类字段 name/description，不显式传参
     */
    constructor(name?: string, description?: string, expandable: boolean = false) {
        this.name = name ?? (this as any).name ?? this.constructor.name;
        this.description = description ?? (this as any).description ?? "";
        this.expandable = expandable ?? (this as any).expandable ?? false;
    }

    /**
     * 执行工具，返回 ToolResponse 对象
     * 
     * @param parameters 工具参数对象
     */
    abstract run(parameters: Record<string, any>): ToolResponse | Promise<ToolResponse>;

    /**
     * 获取工具参数定义
     */
    abstract getParameters(): ToolParameter[];

    /**
     * 执行工具并自动添加时间统计和上下文信息
     * 
     * @param parameters 工具参数对象
     */
    async runWithTiming(parameters: Record<string, any>): Promise<ToolResponse> {
        const startTime = Date.now();

        try {
            const response = await this.run(parameters);
            return this._addStatsAndContext(response, parameters, startTime);
        } catch (e) {
            const elapsedMs = Date.now() - startTime;
            return ToolResponse.error(
                ToolErrorCode.INTERNAL_ERROR,
                `工具执行时发生未处理的异常: ${e instanceof Error ? e.message : String(e)}`,
                { time_ms: elapsedMs },
                { params_input: parameters, tool_name: this.name }
            );
        }
    }

    /**
     * 异步执行工具
     * 
     * @param parameters 工具参数对象
     */
    async arun(parameters: Record<string, any>): Promise<ToolResponse> {
        return this.run(parameters);
    }

    /**
     * 异步执行工具并自动添加时间统计
     * 
     * @param parameters 工具参数对象
     */
    async arunWithTiming(parameters: Record<string, any>): Promise<ToolResponse> {
        return this.runWithTiming(parameters);
    }

    private _addStatsAndContext(response: ToolResponse, parameters: Record<string, any>, startTime: number): ToolResponse {
        const elapsedMs = Date.now() - startTime;

        if (!response.stats) {
            response.stats = {};
        }
        response.stats.time_ms = elapsedMs;

        if (!response.context) {
            response.context = {};
        }
        response.context.params_input = parameters;
        response.context.tool_name = this.name;

        return response;
    }

    /**
     * 获取展开后的子工具列表
     */
    getExpandedTools(): Tool[] | null {
        if (!this.expandable) {
            return null;
        }

        const tools: Tool[] = [];
        // 获取原型上的所有方法
        let currentProto = Object.getPrototypeOf(this);
        while (currentProto && currentProto !== Object.prototype) {
            const propertyNames = Object.getOwnPropertyNames(currentProto);
            for (const name of propertyNames) {
                const method = (this as any)[name];
                if (typeof method === 'function' && method._isToolAction) {
                    // 检查是否已经添加过（子类重写的情况）
                    if (tools.some(t => t instanceof AutoGeneratedTool && t.methodName === name)) {
                        continue;
                    }

                    const tool = new AutoGeneratedTool(
                        this,
                        method.bind(this),
                        method._toolName,
                        method._toolDescription,
                        name,
                        method._toolParameters
                    );
                    tools.push(tool);
                }
            }
            currentProto = Object.getPrototypeOf(currentProto);
        }

        return tools.length > 0 ? tools : null;
    }

    /**
     * 验证参数
     * 
     * @param parameters 参数对象
     */
    validateParameters(parameters: Record<string, any>): boolean {
        const requiredParams = this.getParameters()
            .filter(p => p.required)
            .map(p => p.name);
        return requiredParams.every(param => param in parameters);
    }

    /**
     * 转换为字典格式
     */
    toDict(): Record<string, any> {
        return {
            name: this.name,
            description: this.description,
            parameters: this.getParameters()
        };
    }

    /**
     * 转换为 OpenAI function calling schema 格式
     */
    toOpenAISchema(): Record<string, any> {
        const parameters = this.getParameters();
        const properties: Record<string, any> = {};
        const required: string[] = [];

        for (const param of parameters) {
            const prop: Record<string, any> = {
                type: param.type,
                description: param.description
            };

            if (param.default !== undefined && param.default !== null) {
                prop.description = `${param.description} (默认: ${JSON.stringify(param.default)})`;
            }

            if (param.type === "array") {
                prop.items = { type: "string" };
            }

            properties[param.name] = prop;

            if (param.required) {
                required.push(param.name);
            }
        }

        return {
            type: "function",
            function: {
                name: this.name,
                description: this.description,
                parameters: {
                    type: "object",
                    properties: properties,
                    required: required
                }
            }
        };
    }

    toString(): string {
        return `Tool(name=${this.name})`;
    }
}

/**
 * 自动生成的工具 - 从方法和元数据自动提取
 */
export class AutoGeneratedTool extends Tool {
    parent: Tool;
    method: Function;
    methodName: string;
    private _parameters: ToolParameter[];

    /**
     * 初始化自动生成的工具
     * 
     * @param parent 父工具实例
     * @param method 被装饰的方法
     * @param name 工具名称
     * @param description 工具描述
     * @param methodName 方法名
     * @param parameters 参数定义
     */
    constructor(
        parent: Tool,
        method: Function,
        name?: string,
        description?: string,
        methodName?: string,
        parameters?: ToolParameter[]
    ) {
        const finalMethodName = methodName || (method as any).name || 'unknown';
        const strippedName = finalMethodName.replace(/^_/, '');
        const finalName = name || `${parent.name}_${strippedName}`;
        const finalDescription = description || `执行 ${finalMethodName}`;

        super(finalName, finalDescription);
        this.parent = parent;
        this.method = method;
        this.methodName = finalMethodName;
        this._parameters = parameters || [];
        
        // 注意：在 TS 中自动从 docstring 提取描述和参数较为困难
        // 建议显式在 @toolAction 中提供参数定义
    }

    getParameters(): ToolParameter[] {
        return this._parameters;
    }

    async run(parameters: Record<string, any>): Promise<ToolResponse> {
        try {
            // 在 JS 中，由于没有类似 Python 的 **kwargs 自动解包到位置参数，
            // 我们约定 toolAction 装饰的方法接受一个包含所有参数的对象作为唯一参数
            // 或者子类可以重写此逻辑。
            const result = await this.method(parameters);

            if (result instanceof ToolResponse) {
                return result;
            }

            return ToolResponse.success(
                String(result),
                { output: result }
            );
        } catch (e) {
            return ToolResponse.error(
                ToolErrorCode.EXECUTION_ERROR,
                `方法执行失败: ${e instanceof Error ? e.message : String(e)}`
            );
        }
    }
}
